config/routes.rb
Rails.application.routes.draw do

  resources :messages

  devise_for :users
  get 'posts/index'

  root 'groups#index'

  get 'posts/user_posts' => 'posts#user_posts'
  get 'my_groups' => 'groups#my_groups'

  resources :groups do 
    member do
      get :follow
      get :unfollow
      get :group_members
    end

    resources :posts do
      resources :comments
    end
    resources :members
    
  end

end

app/models/blog.rb
class Blog < ActiveRecord::Base

	#associaton
	belongs_to :user

	
	#validations
	validates_presence_of :title
	validates_presence_of :text
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :post
  belongs_to :user

  validates_presence_of :text
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
	
	#association
	has_many :members
	has_many :users, :dependent => :destroy, :through => :members
	has_many :posts, :dependent => :destroy

	#validations
	validates_presence_of :name

	acts_as_followable

	def display_follow_button?(user, group)
		user.following?(group) && user.id != group.user_id
	end

	def display_unfollow_button?(user, group)
		!user.following?(group) && user.id != group.user_id
	end

	def is_member?(user)
    result = Member.where("user_id = ? and group_id = ? and is_confirmed = ?", user.id, self.id, true).first
    return true if result.present? 
  end

  def is_requested_member?(user)
    result = Member.where("user_id = ? and group_id = ? and is_confirmed = ?", user.id, self.id, false).first
    return true if result.present? 
  end
	
end

app/models/member.rb
class Member < ActiveRecord::Base
  

  belongs_to :user
  belongs_to :group

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base

	#associaton
	belongs_to :user
  has_many :comments

	
	#validations
	validates_presence_of :title
	validates_presence_of :text
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #associations
  has_many :posts, :dependent => :destroy
  has_many :members
  has_many :groups, :dependent => :destroy, :through => :members
  has_many :comments
  has_many :messages

  acts_as_follower
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.post_id = params[:post_id]
    if @comment.save
      redirect_to group_post_path(@comment.post.group_id, @comment.post)
    else
      render 'new'
    end
  end

  def index
    @comments = Comment.where('post_id = ?', params[:post_id] )
  end

  def destroy
    @group = Group.find(params[:group_id])
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @user = current_user
    @comment.destroy
    redirect_to group_post_path(@group.id, @post.id)
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end



end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_action :authenticate_user!
  
  def index
  	@groups = Group.all
  end

  def new
  end

  def show
    @group = Group.find(params[:id])
    @user = User.find(@group.user_id)
    @posts = @group.posts.page(params[:page]).per(4)
    authorize @group
  end

  def create
  	@group = Group.new(group_params)
	  @group.user_id = current_user.id
    if @group.save
      current_user.follow(@group)
	    redirect_to groups_path
    else
      render 'new'
    end
  end

  def edit
    @group = Group.find(params[:id])
    authorize @group
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to group_path(@group)
    else
      render 'edit'
    end
  end

  def my_groups
    @groups = Group.where("user_id = ?", current_user.id)
  end

  def follow
    @group = Group.find(params[:id])
    current_user.follow(@group)
    respond_to do |format|
      if current_user.save
        format.html { redirect_to groups_path }
        format.js {}
      end
    end
  end

  def group_members
    @unconfirmed_members = Member.where("group_id = ? and is_confirmed = ?", params[:id], false)
    @confirmed_members = Member.where("group_id = ? and is_confirmed = ?", params[:id], true)
  end

  def unfollow
    @group = Group.find(params[:id])
    current_user.stop_following(@group)
    respond_to do |format|
      if current_user.save
        format.html { redirect_to groups_path }
        format.js {}
      end
    end
  end

  private
  
  def group_params
    params.require(:group).permit(:name)
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  def index
    @member = Member.all
  end

  def create
    @member = Member.new
    @member.group_id = params[:group_id]
    @member.user_id = current_user.id
    @member.is_confirmed = false
    respond_to do |format|
      if @member.save
        format.html {redirect_to group_path(@member.group_id) }
        format.js {}
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @member = Member.find(params[:id])
    @member.is_confirmed = true
    respond_to do |format|
      if @member.save
        format.html {redirect_to group_path(@member.group_id) }
        format.js {}
      end
    end
  end

  def destroy
    @member = Member.find(params[:id])
    @group = Group.find(params[:group_id])
    @member.destroy
    redirect_to group_path(@group.id)
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Message.all
  end
  
  def create
    @message = Message.new()
    @message.message = params[:message]["message"]
    @message.user_id = current_user.id
    @message.save
    PrivatePub.publish_to("/messages/new", message: @message)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :authenticate_user!
  
  def index
    @posts = Post.all
    @group = Group.find(params[:group_id])
  end
  
  def new
    @group = Group.find(params[:group_id])
  end

  def show
    @post = Post.find(params[:id])
    @user = User.find(@post.user_id)
    @group = Group.find(params[:group_id])
  end

  def create
	  @post = Post.new(post_params)
	  @post.user_id = current_user.id
    @post.group_id = params[:group_id]
	  if @post.save
      redirect_to group_post_path(@post.group_id, @post)
    else
      render 'new'
    end
	end

  def edit
    @group = Group.find(params[:group_id])
    @post = Post.find(params[:id])
    authorize @post
  end

  def update
    @post = Post.find(params[:id])
    @group = Group.find(params[:group_id])
    if @post.update(post_params)
      redirect_to group_post_path(@group, @post)
    else
      render 'edit'
    end
  end

  def destroy
    @group = Group.find(params[:group_id])
    @post = Post.find(params[:id])
    @post.destroy
    authorize @post
    redirect_to group_path(@group.id)
  end

  def user_posts
    @posts = current_user.posts
  end

	private
  
  def post_params
    params.require(:post).permit(:title, :text)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blogs/index.html.erb
<%= button_to "Log out", destroy_user_session_path, method: :delete, style: "position: absolute; right: 50px;" %>
<div class="header">
	<div>
	<h1>GetInfo</h1>
		<%= button_to 'Create Blog', new_blog_path, method: "get", class: "myButton" %>
	</div>
</div>

<div class="div-col">
	<% @blogs.each do |blog|%>
<div class="box" >
		<h2><%= blog.title %></h2>
		<br/>
		<p class="p">
		<%= blog.text %>
	</p>
	<%= button_to 'Read More', blog_path(blog), method: "get" %>
</div>
	<% end %>
</div>

app/views/blogs/new.html.erb
<p class="p"><b>New blog</b></p>
<%= form_for :blogs, url: blogs_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "lable" %>
    <%= f.submit class: "myButton" %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text, class: "styled" %>
  </p>
<% end %>

app/views/blogs/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @blog.text %>
</p>

app/views/groups/_group.html.erb
<div class="box" >		
		<h2><%= link_to_if current_user.following?(group), group.name, group_path(group) %></h2>	
	<%= link_to "Unfollow", unfollow_group_path(group), remote: true , class: "smallButton" if group.display_follow_button?(current_user, group) %>
		
	<%= link_to "Follow", follow_group_path(group), remote: true , class: "smallButton" if group.display_unfollow_button?(current_user, group) %>
	
</div>

app/views/groups/edit.html.erb
<div class="read_post">
<p class="p"><b>Edit Group</b></p>
  <%= form_for :group, method: 'patch', url: group_path(@group) do |f| %>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name, class: "lable", id: 'group_name' %>
    </p>
    <%= f.submit class: "myButton" %>
  <% end %>
</div>

app/views/groups/follow.js.erb
window.location.reload();

app/views/groups/group_members.html.erb
<div class = "requested_users" >
<h3>Requested users</h3>
</br>
<% @unconfirmed_members.each do |m| %>
 <li><%= m.user.email %>
 <%= link_to "confirm", group_member_path(m.group.id, m), method: 'put', remote: true , class: "smallButton" if m.group.user_id == current_user.id %></li>
<% end %>
</div>
</br>
</br>
</br>
<div class = "group_members">
<h3>Members<h3/>
</br>

<% @confirmed_members.each do |m| %>
  <li><%= m.user.email %>
  <%= link_to 'Delete', group_member_path(m.group.id, m), method: :delete, class: "smallButton",
                  data: { confirm: 'Are you sure?' } if m.group.user_id == current_user.id %></li>
<% end %>
</div>

app/views/groups/index.html.erb
<div class="header_link">
	<div>
    <%= link_to 'Create Group', new_group_path, class: "myButton" %>
    <%= link_to 'My Posts', posts_user_posts_path, class: "myButton" %>
    <%= link_to 'My Groups', my_groups_path, class: "myButton" %>
  </div>
</div>


<% flash.each do |key, value| %>
		<%= content_tag :div, value, class: "flash #{key}", id: "flash_messages" %>
<% end %>

<div class="div-col">
	<% @groups.each do |group|%>
		<%= render partial: 'group', locals: {group: group} %>
	<% end %>
</div>

<script>

</script>

app/views/groups/my_groups.html.erb
<div class="div-col">
	<% @groups.each do |group|%>
		<div class="box" >
			<h2><%= link_to group.name, group_path(group)  %></h2>
		</div>
	<% end %>
</div>

app/views/groups/new.html.erb
<div class="read_post">
<p class="p"><b>New Group</b></p>
	<%= form_for :group, url: groups_path do |f| %>
	  <p>
	    <%= f.label :name %><br>
	    <%= f.text_field :name, class: "lable", id: 'group_name' %>
	  </p>
	  <%= f.submit class: "myButton" %>
	<% end %>
</div>

app/views/groups/show.html.erb
<div class = "group_header">
  <%= @group.name %>
</div>


<div class= "group_owner">
  Owner: <%= @user.email %>
  <%= link_to 'Edit Group name', edit_group_path(@group), class: "smallButton" if @group.user_id == current_user.id %>
</div>
<% if @group.user_id != current_user.id %>

  <% if !@group.is_member?(current_user) && !@group.is_requested_member?(current_user)%>
    <%= link_to 'Request member', group_members_path(@group.id), method: 'post', id: "request_member", remote: true, class: "myButton" %>
  <% end %>

<% end %>

<% if @group.is_requested_member?(current_user) %>
  <p class = "smallButton"> Request pending </p>
<% end %>

<% if @group.is_member?(current_user) || @group.user_id == current_user.id %>
  <%= link_to "Create Post", new_group_post_path(@group.id), class: 'myButton' %>
<% end %>

<%= link_to 'Group Members', group_members_group_path(@group), class: "myButton" if @group.user_id == current_user.id %>

<div class="read_post">
	<% @posts.each do |post| %>
		<%= render partial: 'posts/post', locals: {post: post, group: @group} %>
	<% end %>

  <%= paginate @posts %>
</div>

app/views/groups/unfollow.js.erb
window.location.reload();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 <title>GetInfo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-59823135-1', 'auto');
    ga('send', 'pageview');

  </script>
</head>
<body>
  <% if user_signed_in? %>
    <div class = "logout">
      <%= current_user.email %>
  		<%= button_to "Log out", destroy_user_session_path, method: :delete %>
    </div>
  <% end %>
  <div class="header">
		<h1>GetInfo</h1>
	</div>
<%= yield %>


<%= javascript_include_tag :defaults, "http://localhost:9292/faye.js" %>

<div id="footer">developed by : Akshay Simha S R</div>
</body>
</html>

app/views/members/create.js.erb
window.location.reload();

app/views/members/update.js.erb
window.location.reload();

app/views/messages/_message.html.erb
<li>
  <span class="created_at"><strong><%= message.user.email.split('@')[0] if message.user.present? %></strong> : </span>
  <%= message.message %>
</li>

app/views/messages/create.js.erb
<% publish_to "/messages/new" do %>
  $("#chat").append("<%= j render(@message) %>");
  $("#new_message")[0].reset();
<% end %>

app/views/messages/index.html.erb
<h3> Chat </h3>

<ul id="chat">
  <%= render @messages %>
</ul>

<%= form_for Message.new, :remote => true do |f| %>
  <%= f.text_field :message %>
  <%= f.submit "Send" %>
<% end %>

<%= subscribe_to "/messages/new" %>

app/views/posts/_post.html.erb
<div class="post_box" >
		<h2><%= post.title %></h2>
		<br/>
		<p class="p">
		<%= post.text %>
	</p>
	<%= button_to 'Read More', group_post_path(post.group_id, post), method: "get" %>
</div>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_for :post, method: 'patch', url: group_post_path(@post.group_id, @post) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "lable"  %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text, class: "styled" %>
  </p>

  <%= f.submit class: "myButton" %>
<% end %>
 

app/views/posts/index.html.erb
<%= button_to "Log out", destroy_user_session_path, method: :delete, class: "logout" %>
<div class="header">
  <h1>GetInfo</h1>
<div/>
<div class ="header_link">
  <%= link_to 'Create post', new_group_post_path(@group), method: "get", class: "myButton" %>
  <%= link_to 'My post', posts_user_posts_path, method: "get", class: "myButton" %>
</div>

<div class="div-col">
	<% @posts.each do |post|%>
	<%= render partial: 'post', locals: {post: post, group: @group} %>
	<% end %>
</div>

app/views/posts/new.html.erb
<div class="read_post">
<p class="p"><b>New post</b></p>
	<%= form_for :post, url: group_posts_path(@group) do |f| %>
	  <p>
	    <%= f.label :title %><br>
	    <%= f.text_field :title, class: "lable" %>
	  </p>
	 
	  <p>
	    <%= f.label :text %><br>
	    <%= f.text_area :text, class: "styled" %>
	  </p>
	  <%= f.submit class: "myButton" %>
	<% end %>
</div>

app/views/posts/show.html.erb
<div class="read_post">
	<article>
		<p>Written by: <%= @user.email %></p>
		
		<% if @post.user_id == current_user.id %>
			<%= link_to 'Edit', edit_group_post_path(@post.group_id, @post), class: "smallButton" %>
			<%= link_to 'Delete', group_post_path(@group.id, @post), method: :delete,
	              data: { confirm: 'Are you sure?' }, class: "smallButton" %>
		<% end %>
		<p>
		  <h1><u><%= @post.title %></u></h1>
		</p>
	 
		<p class = "blog_content">
		  <%= @post.text %>
		</p>
	</article>


	<article>
		<h1> <u>Comments</u> </h1>
		<% @post.comments.each do |c| %>
			<P>
				Commente by: <%= c.user.email %>
				<%= link_to 'Delete', group_post_comment_path(@group.id, @post, c.id), method: :delete,
	              data: { confirm: 'Are you sure?' }, class: "smallButton" if current_user == c.user || current_user == @post.user %>
	    </P>
			<P><%= c.text %></P>
			<hr/>
		<% end %>
	</article>
	 <%= form_for :comment, url: group_post_comments_path(@post.group_id, @post.id) do |f| %>
	  <p>
	    <%= f.label :comment %><br>
	    <%= f.text_area :text, required: true %>
	  </p>
	  <%= f.submit %>
	 <% end %>
<%= link_to "Home", root_path, class: 'myButton' %>
</div>

app/views/posts/user_posts.html.erb
<div class="div-col">
	<% @posts.each do |post|%>
		<%= render partial: 'post', locals: {post: post} %>
	<% end %>
</div>